### ISSUE TITLE
LAS Discussion

### ISSUE THREAD

**Issue by ju2wheels** [IronicBadger/docker-librevault#2]
[Original Discussion](https://www.reddit.com/r/LinuxActionShow/comments/4zoz6l/librevault_docker/)

This is a GUI based application not a web based application. In order to get this to work you need to set the entrypoint to /usr/bin/librevault-gui and then figure out how to foward your X11 session into the container (and whatever other dependencies you find along the way as you start to run it once you have that going).

**Comment by ju2wheels** [comment]
Scratch what I said, sorry didnt notice it installed librevault-daemon. I think I can get it working give me a few.

**Comment by ju2wheels** [comment]
#3 should resolve your daemon issue (fyi Ive only run the container, not actually tested librevault with it as I dont plan to install it on my server). Let me know if it doesnt work and what you get it if doesnt.

Also what I said above still applies if you want to containerize librevault-gui.

**Comment by ju2wheels** [comment]
I found this [librevault configuration](https://librevault.com/blog/librevault-config/) information but I cant tell if its for both the lirbrevault-daemon and librevault-gui or just the gui. In either case if its applicable to the daemon we just need to create these config files in `/home/librevault/.config/Librevault` and also make this folder a volume and ensure we chown the folder/contents in the start script.

This might work the daemon though because the ports match what I found from the daemon.

**Comment by ju2wheels** [comment]
I opened https://github.com/Librevault/librevault/issues/60 to address the above question. Also please dont merge the PR yet as its missing exposing the IPv6 ports.

**Comment by ju2wheels** [comment]
Alright, this should get you going. Your turn. I added the mount point for the configuration directory per response above, I havent tried connecting to the container with the GUI.

@IronicBadger @sparklyballs

**Comment by sparklyballs** [comment]
usually to get around odd mapping points for apps that use the home folder for config files, it's easiest to make /config the home folder with 

ENV HOME="/config"

in the dockerfile and run the app as abc (linuxserver specific user)

**Comment by ironicbadger** [comment]
Thanks for your comments @ju2wheels - it doesn't look like librevault is quite in a 'dockeriseable' state yet. What I mean is that it's not really quite a headless Linux app in the way that I first thought it was. I'll keep an eye on it though.

**Comment by GamePad64** [comment]
> it's not really quite a headless Linux app in the way that I first thought it was

Yes, it has no means for controlling it from the outside (no web UI and no CLI interface). Well, actually, the GUI can control the daemon using `--attach` flag, but it is not very convenient.

> it doesn't look like librevault is quite in a 'dockeriseable' state yet

Maybe, you can provide some ideas to implement?

**Comment by GamePad64** [comment]
Also, please note, that the repository format has changed, so you may have to update your repository string with: `deb https://releases.librevault.com/debian xenial main`

**Comment by ironicbadger** [comment]
I don't think I'm properly qualified for ideas other than there should be at least a .cfg or .yml file I can edit if no proper CLI or webUI for configuration exists.... 

If you're happy to have me give ideas and have no idea how to implement them myself, then I'm all in!!
